Repository malandrinersdev/desafio-miniaoc, pull requests merged in 2021-12, with the labels that each got.

#3 Mi solución Python a los dos primeros retos en el desafío miniAoC
  soluciones/marcosgnieto/reto-1/README.md
  soluciones/marcosgnieto/reto-1/email_addresses.txt
  soluciones/marcosgnieto/reto-1/find_smart_hackers.py
  soluciones/marcosgnieto/reto-2/generate_troll_password.py
Labels: respondida, language:python

#7 Reto 1: Los hackers astutos + Reto 2: Malo de la Olma de la Loma Mola + Reto 3: Nokia 6310
  soluciones/ejdiezfraile/.gitignore
  soluciones/ejdiezfraile/README.md
  soluciones/ejdiezfraile/reto-1/app.js
  soluciones/ejdiezfraile/reto-2/index.js
  soluciones/ejdiezfraile/reto-2/package-lock.json
  soluciones/ejdiezfraile/reto-2/package.json
  soluciones/ejdiezfraile/reto-2/reto-2.js
  soluciones/ejdiezfraile/reto-2/test/reto-2.test.js
  soluciones/ejdiezfraile/reto-3/index.js
  soluciones/ejdiezfraile/reto-3/package-lock.json
  soluciones/ejdiezfraile/reto-3/package.json
  soluciones/ejdiezfraile/reto-3/reto-3.js
  soluciones/ejdiezfraile/reto-3/test/reto-3.test.js
Labels: respondida, language:javascript

#8 Retos 1, 2 y 3 con php y tests unitarios
  soluciones/migbara/reto-1/composer.json
  soluciones/migbara/reto-1/src/HackersAstutos.php
  soluciones/migbara/reto-1/tests/HackersAstutosTest.php
  soluciones/migbara/reto-2/composer.json
  soluciones/migbara/reto-2/src/PermutarPalabras.php
  soluciones/migbara/reto-2/tests/PermutarPalabrasTest.php
  soluciones/migbara/reto-3/composer.json
  soluciones/migbara/reto-3/src/HackeoNokia.php
  soluciones/migbara/reto-3/tests/HackeoNokiaTest.php
Labels: respondida, language:php

#1 Solución al reto 1, 2 y 3
  soluciones/niltsiar/reto-1/.gitignore
  soluciones/niltsiar/reto-1/build.gradle.kts
  soluciones/niltsiar/reto-1/gradle.properties
  soluciones/niltsiar/reto-1/gradle/wrapper/gradle-wrapper.jar
  soluciones/niltsiar/reto-1/gradle/wrapper/gradle-wrapper.properties
  soluciones/niltsiar/reto-1/gradlew
  soluciones/niltsiar/reto-1/gradlew.bat
  soluciones/niltsiar/reto-1/settings.gradle.kts
  soluciones/niltsiar/reto-1/src/main/kotlin/Main.kt
  soluciones/niltsiar/reto-2/.gitignore
  soluciones/niltsiar/reto-2/build.gradle.kts
  soluciones/niltsiar/reto-2/gradle.properties
  soluciones/niltsiar/reto-2/gradle/wrapper/gradle-wrapper.jar
  soluciones/niltsiar/reto-2/gradle/wrapper/gradle-wrapper.properties
  soluciones/niltsiar/reto-2/gradlew
  soluciones/niltsiar/reto-2/gradlew.bat
  soluciones/niltsiar/reto-2/settings.gradle.kts
  soluciones/niltsiar/reto-2/src/main/kotlin/Main.kt
  soluciones/niltsiar/reto-3/.gitignore
  soluciones/niltsiar/reto-3/build.gradle.kts
  soluciones/niltsiar/reto-3/gradle.properties
  soluciones/niltsiar/reto-3/gradle/wrapper/gradle-wrapper.jar
  soluciones/niltsiar/reto-3/gradle/wrapper/gradle-wrapper.properties
  soluciones/niltsiar/reto-3/gradlew
  soluciones/niltsiar/reto-3/gradlew.bat
  soluciones/niltsiar/reto-3/settings.gradle.kts
  soluciones/niltsiar/reto-3/src/main/kotlin/Main.kt
Labels: respondida, language:kotlin

#12 Solucion reto 1 & 2
  soluciones/andres-cabrera/reto1/Cargo.lock
  soluciones/andres-cabrera/reto1/Cargo.toml
  soluciones/andres-cabrera/reto1/src/main.rs
  soluciones/andres-cabrera/reto2/Cargo.toml
  soluciones/andres-cabrera/reto2/src/main.rs
Labels: respondida, language:rust

#10 Reto 1 ready
  soluciones/obermur/reto-1/MINIAOC_2021_RETO_1/MINIAOC_2021_RETO_1.UnitTests/HackerDetectorTests.cs
  soluciones/obermur/reto-1/MINIAOC_2021_RETO_1/MINIAOC_2021_RETO_1.UnitTests/MINIAOC_2021_RETO_1.UnitTests.csproj
  soluciones/obermur/reto-1/MINIAOC_2021_RETO_1/MINIAOC_2021_RETO_1.sln
  soluciones/obermur/reto-1/MINIAOC_2021_RETO_1/MINIAOC_2021_RETO_1/HackerDetector.cs
  soluciones/obermur/reto-1/MINIAOC_2021_RETO_1/MINIAOC_2021_RETO_1/MINIAOC_2021_RETO_1.csproj
  soluciones/obermur/reto-1/MINIAOC_2021_RETO_1/MINIAOC_2021_RETO_1/Program.cs
  soluciones/obermur/reto-2/MINIAOC_2021_RETO_2/.vs/MINIAOC_2021_RETO_2/xs/UserPrefs.xml
  soluciones/obermur/reto-2/MINIAOC_2021_RETO_2/.vs/MINIAOC_2021_RETO_2/xs/project-cache/MINIAOC_2021_RETO_2-Debug.json
  soluciones/obermur/reto-2/MINIAOC_2021_RETO_2/.vs/MINIAOC_2021_RETO_2/xs/project-cache/MINIAOC_2021_RETO_2.UnitTests-Debug.json
  soluciones/obermur/reto-2/MINIAOC_2021_RETO_2/MINIAOC_2021_RETO_2.UnitTests/HackingToolkitTests.cs
  soluciones/obermur/reto-2/MINIAOC_2021_RETO_2/MINIAOC_2021_RETO_2.UnitTests/MINIAOC_2021_RETO_2.UnitTests.csproj
  soluciones/obermur/reto-2/MINIAOC_2021_RETO_2/MINIAOC_2021_RETO_2.sln
  soluciones/obermur/reto-2/MINIAOC_2021_RETO_2/MINIAOC_2021_RETO_2/HackingToolkit.cs
  soluciones/obermur/reto-2/MINIAOC_2021_RETO_2/MINIAOC_2021_RETO_2/MINIAOC_2021_RETO_2.csproj
  soluciones/obermur/reto-2/MINIAOC_2021_RETO_2/MINIAOC_2021_RETO_2/Program.cs
  soluciones/obermur/reto-3/MINIAOC_2021_RETO_3/.vs/MINIAOC_2021_RETO_3/xs/UserPrefs.xml
  soluciones/obermur/reto-3/MINIAOC_2021_RETO_3/.vs/MINIAOC_2021_RETO_3/xs/project-cache/MINIAOC_2021_RETO_3-Debug.json
  soluciones/obermur/reto-3/MINIAOC_2021_RETO_3/.vs/MINIAOC_2021_RETO_3/xs/project-cache/MINIAOC_2021_RETO_3.UnitTests-Debug.json
  soluciones/obermur/reto-3/MINIAOC_2021_RETO_3/MINIAOC_2021_RETO_3.UnitTests/MINIAOC_2021_RETO_3.UnitTests.csproj
  soluciones/obermur/reto-3/MINIAOC_2021_RETO_3/MINIAOC_2021_RETO_3.UnitTests/NokiaTests.cs
  soluciones/obermur/reto-3/MINIAOC_2021_RETO_3/MINIAOC_2021_RETO_3.sln
  soluciones/obermur/reto-3/MINIAOC_2021_RETO_3/MINIAOC_2021_RETO_3/MINIAOC_2021_RETO_3.csproj
  soluciones/obermur/reto-3/MINIAOC_2021_RETO_3/MINIAOC_2021_RETO_3/Nokia.cs
  soluciones/obermur/reto-3/MINIAOC_2021_RETO_3/MINIAOC_2021_RETO_3/Program.cs
Labels: respondida, language:c#

#6 Reto 1 + Reto 2 (JS + Jest)
  soluciones/sergioedo/reto-1/.gitignore
  soluciones/sergioedo/reto-1/.prettierrc
  soluciones/sergioedo/reto-1/package-lock.json
  soluciones/sergioedo/reto-1/package.json
  soluciones/sergioedo/reto-1/smart-hackers.js
  soluciones/sergioedo/reto-1/smart-hackers.test.js
  soluciones/sergioedo/reto-2/.gitignore
  soluciones/sergioedo/reto-2/.prettierrc
  soluciones/sergioedo/reto-2/package-lock.json
  soluciones/sergioedo/reto-2/package.json
  soluciones/sergioedo/reto-2/troll-pwd.js
  soluciones/sergioedo/reto-2/troll-pwd.test.js
  soluciones/sergioedo/reto-3/.gitignore
  soluciones/sergioedo/reto-3/.prettierrc
  soluciones/sergioedo/reto-3/key-combinations.js
  soluciones/sergioedo/reto-3/key-combinations.test.js
  soluciones/sergioedo/reto-3/letter-combinations.js
  soluciones/sergioedo/reto-3/letter-combinations.test.js
  soluciones/sergioedo/reto-3/package-lock.json
  soluciones/sergioedo/reto-3/package.json
Labels: respondida, language:javascript

#11 Solución retos 1, 2 y 3
  soluciones/alexhermida/reto-1/.gitignore
  soluciones/alexhermida/reto-1/Cargo.lock
  soluciones/alexhermida/reto-1/Cargo.toml
  soluciones/alexhermida/reto-1/README.md
  soluciones/alexhermida/reto-1/src/main.rs
  soluciones/alexhermida/reto-2/.gitignore
  soluciones/alexhermida/reto-2/Cargo.lock
  soluciones/alexhermida/reto-2/Cargo.toml
  soluciones/alexhermida/reto-2/README.md
  soluciones/alexhermida/reto-2/src/main.rs
  soluciones/alexhermida/reto-3-python/README.md
  soluciones/alexhermida/reto-3-python/main.py
  soluciones/alexhermida/reto-3-python/requirements.txt
  soluciones/alexhermida/reto-3-python/test_main.py
Labels: respondida, language:rust

#2 Solución reto y con php :)
  soluciones/karlos/reto-1/index.php
Labels: respondida, language:php

#4 Reto 1 y 2: F# solution
  soluciones/xurxof/.gitignore
  soluciones/xurxof/Reto2/GenerateTrollPassword.fs
  soluciones/xurxof/Reto2/Program.fs
  soluciones/xurxof/Reto2/Reto2.fsproj
  soluciones/xurxof/Reto2/testing.fs
  soluciones/xurxof/miniAoC.sln
  soluciones/xurxof/miniAoC/Program.fs
  soluciones/xurxof/miniAoC/miniAoC.fsproj
  soluciones/xurxof/miniAoC/reto1.fs
  soluciones/xurxof/miniAoC/testing.fs
  soluciones/xurxof/readme.txt
Labels: respondida, language:f#

#9 Add the solution to the first challenge
  soluciones/guillermoig/.gitignore
  soluciones/guillermoig/reto-1/AntiSpam.py
  soluciones/guillermoig/reto-1/main.py
  soluciones/guillermoig/reto-1/test_AntiSpam.py
  soluciones/guillermoig/reto-2/PasswordGenerator.py
  soluciones/guillermoig/reto-2/main.py
  soluciones/guillermoig/reto-2/test_PasswordGenerator.py
  soluciones/guillermoig/reto-3/parte-1/WordGenerator.py
  soluciones/guillermoig/reto-3/parte-1/main.py
  soluciones/guillermoig/reto-3/parte-1/test_WordGenerator.py
  soluciones/guillermoig/reto-3/parte-2/LettersEncoder.py
  soluciones/guillermoig/reto-3/parte-2/main.py
  soluciones/guillermoig/reto-3/parte-2/test_LettersEncoder.py
Labels: respondida, language:python

#5 Ramon Ruiz: challenge 1
  soluciones/ramon-ruiz/reto-1/reto-1.js
Labels: respondida, language:javascript

#15 Solución al reto 3
  soluciones/prinhelmet/reto3-sol.php
Labels: respondida, language:php
